name: Update Activity

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: canaytore/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: canaytore
          GIST_ID: 84650f212ec6b057d1aec6ea448b29d9
