name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update the README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: ${{ secrets.UPDATE_README_WORKFLOW }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
