name: Update badges

on:
  schedule:
    # Runs at 0AM UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Credly badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREDLY_USER: canaytore
          BADGE_SIZE: 140
          NUMBER_LAST_BADGES: 24
