name: Update badges

on:
  schedule:
    # Runs at 1AM UTC
    - cron: "0 1 * * *"
jobs:
  update-readme:
    name: Update Readme with Credly badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: can-aytore
